---
title: '508 Final: Heroin Overdose Prediction'
author: "Jingyi Li & Sihan Ren"
date: "2023-11-29"
output: html_document
---

## Set Up

```{r setup, include=FALSE}
library(geos)
library(rsgeo)
library(tidyverse)
library(tidycensus)
library(sf)
library(kableExtra)
library(knitr)
library(dplyr)
library(spdep)
library(caret)
library(ckanr)
library(FNN)
library(grid)
library(gridExtra)
library(ggcorrplot)
library(stargazer)
```

## Data

```{r cars}
drugOverdose<-read.csv("DATA/Fire_and_Medical_Opioid_Overdose_Incidents.csv")%>%
  mutate(X = as.numeric(Longitude),Y = as.numeric(Latitude)) %>% 
    na.omit() %>%
    st_as_sf(coords = c("X", "Y"), crs = 4326, agr = "constant")%>%
    st_transform('EPSG:2223')%>%
    distinct()
crime<-read.csv("DATA/Crime_Reporting_Statistics.csv")%>%
  mutate(X = as.numeric(Longitude),Y = as.numeric(Latitude)) %>% 
    na.omit() %>%
    st_as_sf(coords = c("X", "Y"), crs = 4326, agr = "constant")%>%
    st_transform('EPSG:2223')%>%
    distinct()
graffiti<- read.csv("DATA/Transportation_Graffiti_20231129.csv")%>%
  mutate(X = as.numeric(Longitude),Y = as.numeric(Latitude)) %>% 
    na.omit() %>%
    st_as_sf(coords = c("X", "Y"), crs = 4326, agr = "constant")%>%
    st_transform('EPSG:2223')%>%
    distinct()
homeless<-read.csv("DATA/Unsheltered_Point_in_Time__PIT__Count_Phoenix_Metro_Area_20231129.csv")%>%
  mutate(X = as.numeric(Longitude),Y = as.numeric(Latitude)) %>% 
    na.omit() %>%
    st_as_sf(coords = c("X", "Y"), crs = 4326, agr = "constant")%>%
    st_transform('EPSG:2223')%>%
    distinct()
census20<-  get_acs(geography = "block group",
          variables = c("B19013_001E",# medHH income
                        "B01003_001E",#total pop
                        "B15003_022E",# bachelor or more
                        "B23025_005E",# unemployed
                        "B02008_002E",# white alone
                        "B02009_002E"),#black alone
          year=2020, state=04,
          county=13, geometry=TRUE) %>% 
  st_transform('EPSG:2223')

census20<-census%>%
  dplyr::select( -NAME, -moe) %>%
  spread(key = variable, value = estimate) %>%
  rename(TotalPop = B01003_001E, 
         MedHHInc = B19013_001E, 
         BachMore = B150003_22E,
         Unemploy = B23025_005E,
         BlackAlone = B02009_002E,
         WhiteAlone = B02008_002E
         )

census20<- 
  census %>%
  mutate(pctUnemploy = ifelse(TotalPop > 0, Unemploy / TotalPop, 0),
         pctWhite = ifelse(TotalPop > 0, (WhiteAlone / MobilityTotal), 0),
         pctBlack = ifelse(TotalPop > 0, BlackAlone / TotalPop, 0,),
         pctBachMore= ifelse(TotalPop>0, BachMore / TotalPop, 0,),
         year = "2020") %>%
  dplyr::select(-BachMore,-Unemploy,-BlackAlone,-WhiteAlone)
```

## Explore

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

